/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const init_panic_hook: () => void;
export const prove_verify_test_export_json: (a: number, b: number) => [number, number, number];
export const __wbg_neofoldsession_free: (a: number, b: number) => void;
export const neofoldsession_new: (a: number, b: number) => [number, number, number];
export const neofoldsession_step_count: (a: number) => number;
export const neofoldsession_setup_timings_ms: (a: number) => [number, number, number];
export const neofoldsession_params_summary: (a: number) => [number, number, number];
export const neofoldsession_circuit_summary: (a: number) => [number, number, number];
export const neofoldsession_add_step_witness_json: (a: number, b: number, c: number) => [number, number];
export const neofoldsession_add_step_io_json: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const neofoldsession_add_steps_from_test_export_json: (a: number, b: number, c: number) => [number, number];
export const neofoldsession_set_step_linking_pairs_json: (a: number, b: number, c: number) => [number, number];
export const neofoldsession_fold_and_prove: (a: number) => [number, number, number];
export const neofoldsession_verify: (a: number, b: number) => [number, number, number];
export const neofoldsession_spartan_prove: (a: number, b: number) => [number, number, number];
export const neofoldsession_spartan_verify: (a: number, b: number) => [number, number, number];
export const __wbg_neofoldproof_free: (a: number, b: number) => void;
export const neofoldproof_step_count: (a: number) => number;
export const neofoldproof_fold_step_ms: (a: number) => [number, number, number];
export const neofoldproof_proof_estimate: (a: number) => [number, number, number];
export const neofoldproof_folding_summary: (a: number) => [number, number, number];
export const __wbg_spartancompressedproof_free: (a: number, b: number) => void;
export const spartancompressedproof_bytes_len: (a: number) => [number, number, number];
export const spartancompressedproof_bytes: (a: number) => [number, number, number, number];
export const spartancompressedproof_vk_bytes_len: (a: number) => [number, number, number];
export const spartancompressedproof_vk_and_snark_bytes_len: (a: number) => number;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
